---
- name: Import Grafana prerequisites tasks
  ansible.builtin.import_tasks: prerequisites.yml

- name: Import Grafana repository setup tasks
  ansible.builtin.import_tasks: repository.yml

- name: Import Grafana installation tasks
  ansible.builtin.import_tasks: install.yml

- name: Import Grafana configuration tasks
  ansible.builtin.import_tasks: configure.yml

- name: Import Grafana datasource setup tasks
  ansible.builtin.import_tasks: datasource.yml

- name: Import Grafana dashboards provisioning tasks
  ansible.builtin.import_tasks: dashboards.yml
