---
# tasks/common.yaml

- name: Install common prerequisites (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
    cache_valid_time: "{{ common_apt_cache_valid_time }}"
  when: ansible_os_family == "Debian"
  become: true

- name: Install common prerequisites (RedHat/CentOS)
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"
  become: true

- name: Ensure vmuser group exists
  ansible.builtin.group:
    name: "{{ vm_group }}"
    state: present
  become: true

- name: Ensure vmuser user exists
  ansible.builtin.user:
    name: "{{ vm_user }}"
    group: "{{ vm_group }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
    state: present
  become: true
